/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class USBThermometerLib_USBThermometerLib */

#ifndef _Included_USBThermometerLib_USBThermometerLib
#define _Included_USBThermometerLib_USBThermometerLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     USBThermometerLib_USBThermometerLib
 * Method:    GetDevicesIds
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_USBThermometerLib_USBThermometerLib_GetDevicesIds
  (JNIEnv *, jobject);

/*
 * Class:     USBThermometerLib_USBThermometerLib
 * Method:    OpenDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_USBThermometerLib_USBThermometerLib_OpenDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     USBThermometerLib_USBThermometerLib
 * Method:    CloseDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_USBThermometerLib_USBThermometerLib_CloseDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     USBThermometerLib_USBThermometerLib
 * Method:    GetDeviceSerial
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_USBThermometerLib_USBThermometerLib_GetDeviceSerial
  (JNIEnv *, jobject, jint);

/*
 * Class:     USBThermometerLib_USBThermometerLib
 * Method:    GetSensorsIds
 * Signature: (I)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_USBThermometerLib_USBThermometerLib_GetSensorsIds
  (JNIEnv *, jobject, jint);

/*
 * Class:     USBThermometerLib_USBThermometerLib
 * Method:    StartConversion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_USBThermometerLib_USBThermometerLib_StartConversion
  (JNIEnv *, jobject, jint);

/*
 * Class:     USBThermometerLib_USBThermometerLib
 * Method:    GetTemperture
 * Signature: (I[B)D
 */
JNIEXPORT jdouble JNICALL Java_USBThermometerLib_USBThermometerLib_GetTemperture
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
